import { Random } from '@wieslawsoltes/ski-core';
import { HILLS } from '@wieslawsoltes/ski-hills';
import { Competition, TourSchedule, competitionCSV, createField, normalizePlayer } from '@wieslawsoltes/ski-competition';
import { JumpSimulation } from '@wieslawsoltes/ski-physics';
import { ReplayPlayer, ReplayRecorder } from '@wieslawsoltes/ski-replay';
import { GameStore } from '@wieslawsoltes/ski-storage';
import { SkiRenderer } from '@wieslawsoltes/ski-renderer';
import { SkiAudio } from '@wieslawsoltes/ski-audio';
import { SkiInput } from '@wieslawsoltes/ski-input';
import * as UI from '@wieslawsoltes/ski-ui';

const tour = new TourSchedule(HILLS.slice(0,3).map(h=>h.id),'TEST').insert('fin').move(0,1).reverse().shuffle(2);
const roundTrip: TourSchedule = TourSchedule.parse(tour.serialize());
const players = createField([normalizePlayer({name:'TEST'})],3);
const cup = new Competition({hills:roundTrip.hills,players});
const bib: number | undefined = cup.startList()[0]?.bib;
const target: number | undefined = cup.target(54)?.distance;
const exported: string = competitionCSV(cup);
const sim = new JumpSimulation(HILLS[0]);
const recorder = new ReplayRecorder(sim,players[0]); recorder.capture(true);
const replay = recorder.finish(); const player = new ReplayPlayer(replay);
const time: number = player.stepFrame(-1).time;
player.jumpTo('takeoff'); player.setLoop(0,1); player.speed=-1; player.update(.01);
const store = new GameStore(null); store.saveTour(tour); store.hillLeaderboard('fin',false,10);
store.personalBests('TEST'); store.renameReplay('id','NAME');
const renderer = new SkiRenderer(document.body); renderer.setHill(HILLS[0]); renderer.render(sim.state,players[0]); renderer.dispose();
const audio = new SkiAudio({volume:.5}); audio.setVolume(.2); audio.dispose();
const inputClass: typeof SkiInput = SkiInput;
const random: number = new Random(1).next();
void [bib,target,exported,time,inputClass,random,UI];

const original = new JumpSimulation('fin', {rules:'dsj210'});
const footAccepted: boolean = original.landingFoot('left');
const originalCup = new Competition({players, rules:'dsj210'});
store.recordKey('fin',false,'dsj210'); store.resetRecords(false,'dsj210');
const input = new SkiInput(document.body, {}, {rules:'dsj210',control:'classic'});
input.virtualButton('right',true); input.dispose();
const classicSize: number = UI.CLASSIC_HUD_LAYOUT.statusHeight;
void [footAccepted, originalCup, classicSize];

import { getHillVisual, HILL_VISUALS } from '@wieslawsoltes/ski-hills';
import { createClassicHillScene } from '@wieslawsoltes/ski-renderer';
const visual = getHillVisual('fin');
const vertices: Float32Array = createClassicHillScene('fin').vertices;
const bands: readonly (readonly number[])[] = visual.inrunBands;
const rendered = new SkiRenderer(document.body,{presentation:'classic'});
const readback: Promise<{width:number;height:number;pixels:Uint8Array}> = rendered.captureFrame();
void [HILL_VISUALS, vertices, bands, readback];
