"""Classic menu regressions: DOM behavior, native-pixel layout and all menu families.

The screenshots are OUR regression captures, not original-game parity certificates.
No game downloads, original fonts, photos, screenshots or binaries are required.
"""
from pathlib import Path
from playwright.sync_api import sync_playwright
from PIL import Image, ImageDraw
import os, json, re, hashlib
ROOT=Path(__file__).resolve().parents[1]
HTML=(ROOT/'SkiJumpWeb.html').read_text()
HTML=re.sub(r"if\s*\(\s*new URLSearchParams\(location\.search\)\.has\(['\"]debug['\"]\)\s*\)",'if (true)',HTML)
HTML=HTML.replace("require('app');", "globalThis.__TEST_MODULES__=require;require('app');")
SHOTS=ROOT/'artifacts/ui';SHOTS.mkdir(parents=True,exist_ok=True)
checks=[];errors=[];screens=[]
def check(v,name):
    assert v,name
    checks.append(name);print('PASS',name,flush=True)
def boot(browser,width=800,height=600,touch=False):
    ctx=browser.new_context(viewport={'width':width,'height':height},has_touch=touch,is_mobile=touch)
    p=ctx.new_page();p.on('pageerror',lambda e:errors.append(str(e)));p.set_content(HTML)
    p.wait_for_function("!!globalThis.__SKI_DEBUG__&&SkiJumpWeb.diagnostics().backend!=='initializing'")
    p.evaluate('cancelAnimationFrame(__SKI_DEBUG__.frameId)');return p
def capture(p,name):
    p.evaluate('__SKI_DEBUG__.menuSkin.refresh()');p.locator('#menu-layer').screenshot(path=str(SHOTS/(name+'.png')))
    screens.append(name)
def opened(p,js,name):
    p.evaluate(js);p.wait_for_timeout(30);capture(p,name)
    check(p.evaluate("()=>{const a=__SKI_DEBUG__,r=a.menu.getBoundingClientRect();return a.menu.classList.contains('classic-ui')&&Math.abs(r.width/r.height-1.6)<1e-5&&a.menu.offsetWidth===320&&a.menu.offsetHeight===200}"),name+' uses the fixed 320x200 surface')
with sync_playwright() as pw:
    browser=pw.chromium.launch(executable_path=os.getenv('CHROMIUM','/usr/bin/chromium'),headless=True,args=['--no-sandbox','--enable-unsafe-webgpu','--enable-unsafe-swiftshader','--use-angle=swiftshader','--use-gl=angle','--ignore-gpu-blocklist'])
    p=boot(browser);capture(p,'main')
    check(p.locator('#menu-layer').evaluate('e=>[e.offsetWidth,e.offsetHeight]')==[320,200],'classic menu is 320x200 independent of browser dimensions')
    check(p.evaluate("__SKI_DEBUG__.menuSkin.viewport.scale")==2,'800x600 window uses integer 2x scaling')
    check(p.locator('.main-menu [data-action]').evaluate_all('a=>a.map(e=>e.dataset.action)')==['world','team','practice','records','replays','sound','quit'],'observed main-menu ordering has no web entries inserted')
    check(p.locator('#menu-layer .classic-extensions').count()==0 and p.locator('#classic-menu-host [data-action=options]').is_visible(),'browser extensions are outside the classic picture')
    check(p.locator('#menu-content').inner_text().count('WORLD CUP')==1,'semantic text appears exactly once, not duplicated by bitmap ink')
    check(p.evaluate("SkiJumpWeb.version==='0.5.0'"),'public game version identifies the UI release')
    check(p.locator('#logo').evaluate('e=>[e.width,e.height]')==[122,27],'classic logo uses its native bitmap dimensions')
    check(p.locator('.main-menu [data-action]').evaluate_all("els=>{const scale=__SKI_DEBUG__.menuSkin.viewport.scale;return els.slice(1,6).every((el,i)=>Math.abs((el.getBoundingClientRect().top-els[i].getBoundingClientRect().top)/scale-12)<.01)}"),'original-style main-menu rows use a twelve-pixel interval')
    before=p.locator('.classic-backdrop').evaluate('c=>c.toDataURL()');p.wait_for_timeout(60)
    check(before==p.locator('.classic-backdrop').evaluate('c=>c.toDataURL()'),'menu backdrop is static rather than a moving hill')
    check(p.evaluate("document.activeElement.dataset.action")== 'world','initial keyboard focus starts at first original menu entry')
    p.keyboard.press('ArrowDown');check(p.evaluate("document.activeElement.dataset.action")=='team','Down moves to the next menu item once')
    p.keyboard.press('End');check(p.evaluate("document.activeElement.dataset.action")=='quit','End selects last menu entry')
    p.keyboard.press('Home');p.keyboard.press('p');check(p.evaluate("document.activeElement.dataset.action")=='practice','type-ahead selects a matching menu entry')
    p.keyboard.press('Enter');check(p.evaluate('__SKI_DEBUG__.view')=='hills','Enter activates the focused item rather than a hard-coded action')
    capture(p,'hills');p.keyboard.press('Escape');check(p.evaluate("document.activeElement.dataset.action")=='practice','Back restores focus to the control used to leave the main menu')
    opened(p,'__SKI_DEBUG__.showRecords()','records')
    check(p.locator('.classic-record').count()==8,'records retains eight-row pagination')
    check(p.locator('#menu-layer .classic-record-tools').count()==0,'board extensions do not change the original records composition')
    opened(p,'__SKI_DEBUG__.confirmResetRecords()','reset-dialog');p.keyboard.press('Escape');check(p.evaluate('__SKI_DEBUG__.view')=='records','Escape cancels record reset')
    opened(p,'__SKI_DEBUG__.showSound()','sound')
    p.locator('[data-setting=volume]').fill('0.4');check(p.evaluate('__SKI_DEBUG__.settings.volume')==.4,'skinned range controls still change actual mixer settings')
    opened(p,'__SKI_DEBUG__.showOptions()','options-display')
    check(p.locator('[role=tab]').count()==3,'all options remain available in three compact tabs')
    p.locator('[data-setting=weather]').click();check(p.locator('.classic-select-popup').is_visible(),'pointer opens a skinned, accessible select popup')
    p.locator('.classic-select-popup').get_by_role('option',name='SNOW',exact=True).click();check(p.evaluate('__SKI_DEBUG__.settings.weather')=='snow','skinned select dispatches the real setting change')
    p.locator('[data-setting=weather]').focus();p.keyboard.press('Enter');p.keyboard.press('Escape');check(p.evaluate('__SKI_DEBUG__.view')=='options' and p.locator('.classic-select-popup').count()==0,'Escape closes only the select popup and restores its control')
    p.locator('[data-tab=controls]').click();capture(p,'options-controls');check(p.locator('[data-setting=sensitivity]').is_visible(),'controls tab exposes sensitivity and input settings')
    p.locator('[data-tab=gameplay]').click();capture(p,'options-gameplay');check(p.locator('[data-setting=windBase]').is_visible(),'gameplay tab exposes practice overrides')
    p.locator('[data-tab=display]').click();p.locator('[data-setting=presentation]').select_option('enhanced')
    check(not p.locator('#menu-layer').evaluate("e=>e.classList.contains('classic-ui')"),'enhanced presentation remains selectable without reload')
    check(p.locator('.options-pane').count()==0,'switching to enhanced restores the complete form rather than hiding settings')
    p.locator('[data-setting=presentation]').select_option('classic');check(p.locator('.classic-tabs').is_visible(),'returning to classic restores the scoped pixel skin')
    opened(p,'__SKI_DEBUG__.showPlayers()','players')
    field=p.locator('#player-name');field.fill('ALPHA <B> & BETA');field.press('End');field.press('Backspace');field.press('A')
    check(field.input_value()=='ALPHA <B> & BETA','native text editing is preserved underneath bitmap rendering')
    check(p.locator('#player-name').evaluate('e=>!!e.parentElement.querySelector(".classic-value")'),'editable values use bitmap overlays rather than a system font')
    p.locator('[data-action=save-players]').click();check(p.evaluate('__SKI_DEBUG__.players[0].name')=='ALPHA B & BETA','editing preserves the existing player normalization contract')
    opened(p,"__SKI_DEBUG__.showSetup('world')",'world-cup')
    check(p.locator('[data-hill]').count()==32,'compact cup setup still includes all 32 hills')
    opened(p,'__SKI_DEBUG__.showTourEditor()','tour-editor')
    p.locator('[data-action=tour-duplicate]').first.click();check(p.evaluate('__SKI_DEBUG__.tour.hills.length')==9,'classic tour buttons edit the real schedule')
    opened(p,"__SKI_DEBUG__.showSetup('team')",'team-cup')
    opened(p,'__SKI_DEBUG__.showHelp()','help')
    opened(p,'__SKI_DEBUG__.showAbout()','about')
    # Real simulation data, not fabricated result rows.
    p.evaluate("()=>{const a=__SKI_DEBUG__;a.seed=42;a.settings.windBase=1;a.settings.windStrength=0;a.startPractice('fin',true);cancelAnimationFrame(a.frameId);const {CPUController}=__TEST_MODULES__('@wieslawsoltes/ski-physics'),cpu=new CPUController(42,.98);while(a.sim.state.phase!=='finished'){cpu.update(a.sim);a.sim.step();a.recorder.capture();}a.finishJump();a.store.saveReplay(a.lastReplay);}")
    capture(p,'result');check(p.locator('.judge').count()==5,'results display all five real judge marks')
    opened(p,'__SKI_DEBUG__.showReplays()','replay-library')
    p.locator('[data-action=replay-details]').first.click();capture(p,'replay-detail')
    check('LENGTH' in p.locator('#menu-content').inner_text(),'classic replay selection opens metadata before playback')
    p.locator('[data-action=delete-replay]').click();capture(p,'delete-dialog');p.keyboard.press('Escape')
    check(p.evaluate('__SKI_DEBUG__.store.replays().length')==1,'canceling delete keeps the replay')
    p.locator('[data-action=replay-details]').first.click();p.locator('[data-action=rename-replay]').click();p.locator('#replay-name').fill('TEST REPLAY');p.locator('[data-action=confirm-rename-replay]').click()
    check('TEST REPLAY' in p.locator('.replay-list').inner_text(),'replay renaming updates visible bitmap and semantic text')
    p.locator('[data-action=replay-details]').first.click();p.locator('[data-action=play-replay]').click()
    check(p.evaluate('__SKI_DEBUG__.view')=='replay' and not p.locator('#classic-menu-host').is_visible(),'playback hides all menu host controls')
    p.locator('[data-replay=back]').click()
    p.evaluate("()=>{const a=__SKI_DEBUG__;const {Competition,createField}=__TEST_MODULES__('@wieslawsoltes/ski-competition');a.cup=new Competition({hills:['eng'],players:createField(a.players,7),rules:'dsj210'});a.mode='world';a.showStartList();}")
    capture(p,'start-list');check(p.locator('tbody tr').count()==8,'start list presents the real eight-jumper field')
    p.locator('[data-action=live-results]').click();capture(p,'live-standings');p.keyboard.press('Escape')
    p.evaluate("()=>{const a=__SKI_DEBUG__,c=a.cup;const {simulateCPU}=__TEST_MODULES__('@wieslawsoltes/ski-physics');while(c.status==='running'){c.submit(simulateCPU(c.hill,{...c.options(),skill:.9}));}a.showEvent();}")
    capture(p,'event-results');check(p.locator('tbody tr').count()==8,'event results use completed two-round scores')
    opened(p,'__SKI_DEBUG__.showCupStandings()','cup-standings')
    opened(p,'__SKI_DEBUG__.showCupHistory()','cup-history')
    p.locator('[data-action=history-event]').first.click();capture(p,'history-event')
    check(p.locator('tbody tr').count()==8,'event-history screen retains all competitor rows')
    p.evaluate("()=>{const a=__SKI_DEBUG__;const {Competition,createTeams}=__TEST_MODULES__('@wieslawsoltes/ski-competition');const teams=createTeams(a.players,3);a.cup=new Competition({mode:'team',hills:['fin'],teams,players:teams.flatMap(t=>t.members)});a.mode='team';a.showTeamDetails(teams[0].id);}")
    capture(p,'team-detail');check(p.locator('tbody tr').count()==4,'team detail presents each of the four athletes')
    # At native scale every bitmap label remains on the same 320x200 surface.
    native=boot(browser,320,260);check(native.evaluate('__SKI_DEBUG__.menuSkin.viewport.scale')==1,'native-size desktop preserves 1:1 pixels')
    capture(native,'main-native')
    check(native.evaluate("()=>{const a=__SKI_DEBUG__,r=a.menu.getBoundingClientRect(),h=a.menuHost.getBoundingClientRect();return r.top>=0&&r.bottom<h.top&&getComputedStyle(a.arena).overflow==='visible'&&r.top===Math.round(r.top)}"),'native frame is pixel-aligned, unclipped and clear of browser controls')
    native.evaluate('__SKI_DEBUG__.showRecords()');capture(native,'records-native')
    mobile=boot(browser,390,844,True);capture(mobile,'portrait')
    check(mobile.evaluate('__SKI_DEBUG__.menuSkin.viewport.scale')==1,'portrait preserves the same logical grid rather than reflowing the classic screen')
    check(mobile.locator('[data-host-command=ArrowDown]').bounding_box()['height']>=44,'mobile navigation has independent 44px touch controls')
    mobile.locator('[data-host-command=ArrowDown]').tap();check(mobile.evaluate('document.activeElement.dataset.action')=='team','touch host preserves and moves the actual menu focus')
    mobile.locator('[data-host-command=ArrowDown]').tap();mobile.locator('[data-host-command=activate]').tap();check(mobile.evaluate('__SKI_DEBUG__.view')=='hills','touch OK activates the selected original menu entry')
    mobile.set_viewport_size({'width':844,'height':390});mobile.wait_for_timeout(40);capture(mobile,'landscape')
    check(mobile.evaluate('__SKI_DEBUG__.view')=='hills','rotation preserves active screen and selection')
    mobile.locator('[data-host-command=fit]').tap();check(mobile.evaluate('__SKI_DEBUG__.menuSkin.viewport.scale')>1,'optional FIT expands touch display without changing the logical layout')
    check(mobile.evaluate("()=>__SKI_DEBUG__.menu.getBoundingClientRect().bottom<__SKI_DEBUG__.menuHost.getBoundingClientRect().top"),'fitted landscape frame never overlaps touch controls')
    mobile.evaluate('__SKI_DEBUG__.showOptions()');mobile.locator('[data-setting=weather]').focus()
    mobile.locator('[data-host-command=activate]').tap()
    check(mobile.locator('.classic-select-popup').is_visible(),'touch OK opens the focused native select through the pixel popup')
    mobile.locator('[data-host-command=back]').tap()
    check(mobile.evaluate('__SKI_DEBUG__.view')=='options' and mobile.locator('.classic-select-popup').count()==0,'touch Back closes a select before navigating away')
    mobile.locator('[data-host-command=back]').tap()
    check(mobile.evaluate('__SKI_DEBUG__.view')=='main','second touch Back returns to main after closing the popup')
    mobile.evaluate('__SKI_DEBUG__.showHills()')
    mobile.locator('[data-action=hill][data-id=fin]').tap();check(mobile.evaluate('__SKI_DEBUG__.view')=='game','touch hill selection starts the real game')
    mobile.keyboard.press('Space');check(mobile.evaluate('__SKI_DEBUG__.sim.state.phase')=='inrun','hidden menu focus cannot swallow gameplay input')
    tiny=boot(browser,320,220,True)
    check(tiny.evaluate("()=>{const a=__SKI_DEBUG__,r=a.menu.getBoundingClientRect(),h=a.menuHost.getBoundingClientRect();return r.top>=0&&r.bottom<h.top&&r.width<=innerWidth}"),'sub-native touch window reserves the measured wrapped control height')
    # Lifecycle test on a detached host; restoration must preserve values and semantics.
    check(p.evaluate("()=>{const {ClassicMenuSkin}=__TEST_MODULES__('@wieslawsoltes/ski-ui');const root=document.createElement('div');root.innerHTML='<label>PLAYER NAME<input value=\"A\"></label><button>SAVE AND BACK</button>';document.body.append(root);const skin=new ClassicMenuSkin(root);skin.setActive(true);skin.layout(640,400);skin.enter('test');const dimensions=root.offsetWidth===320&&root.offsetHeight===200;skin.dispose();skin.dispose();const ok=dimensions&&!root.id&&!root.style.getPropertyValue('--ui-scale')&&root.textContent==='PLAYER NAMESAVE AND BACK'&&root.querySelector('input').value==='A'&&!root.querySelector('canvas');root.remove();return ok;}"),'disposing a reusable skin restores text, values and DOM without duplication')
    check(not errors,'all classic UI workflows finish without JavaScript errors')
    report={'version':json.loads((ROOT/'package.json').read_text())['version'],'status':'passed','checks':len(checks),'passed':checks,'errors':errors,'screens':screens,'bundleSha256':hashlib.sha256((ROOT/'dist/app.js').read_bytes()).hexdigest(),'originalPixelParity':'unverified','scope':'Semantic input, fixed-grid layout, owned bitmap artwork, keyboard/touch and lifecycle tests. Not original-game pixel equality.'}
    (ROOT/'artifacts/browser-ui.json').write_text(json.dumps(report,indent=2)+'\n');browser.close()
# Own-artwork contact sheet; captures are scaled explicitly for this overview only.
thumbs=[]
for name in screens:
    im=Image.open(SHOTS/(name+'.png')).convert('RGB');im=im.resize((320,200),Image.Resampling.NEAREST);thumbs.append((name,im))
contact=Image.new('RGB',(960,224*((len(thumbs)+2)//3)),(10,15,19));draw=ImageDraw.Draw(contact)
for i,(name,im) in enumerate(thumbs):
    x=(i%3)*320;y=(i//3)*224;contact.paste(im,(x,y+20));draw.text((x+5,y+3),name,fill=(220,225,180))
contact.save(SHOTS/'contact.png')
print(json.dumps(report,indent=2))
